[package]
name = "day12"
version = "0.1.0"
authors = ["Erin Hensel <hens0093@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.7.8"

[features]
part2 = []
